### ISSUE TITLE
cachebust.js

### ISSUE THREAD

**Issue by seminull** [furzeface/cachebust#1]
I was reading over the cachebust.js.  It looks like it's getting an MD5 checksum on the fileContents of the given html file, and not whatever the fileContents of the given scriptSrc/styleHref.  Was this intentional?

**Comment by davinkevin** [comment]
Solved in PR https://github.com/furzeface/cachebust/pull/2 - Very important for us

**Comment by furzeface** [comment]
Okydoky, not sure what it is but I'll merge it and do a release. The project I wrote this for is not in use anymore anyway, looking for a maintainer if this plugin is still useful for anyone :grinning:
