### ISSUE TITLE
Cachebust consider <script> tag without src attribute and failed

### ISSUE THREAD

**Issue by spywen** [furzeface/cachebust#6]
Hi !
I have a problem with the current version of cachebust. 
I'm working with davinkevin which sent to you a message earlier : https://github.com/furzeface/cachebust/issues/1

Actually the problem is : if a script tag is inside our base file and this tag don't contain src attribute : cachebust failed unfortunately ;(
--> at line 50 "scripts[j].attribs.src.split("?")[0];" because src is undefined

I prepared a push request for you ;) 
Let me know if you can published this fix as soon as possible ?!

**Comment by spywen** [comment]
Thanks for your time !

**Comment by TyBoss** [comment]
Hey @spywen thanks for creating the ticket request. A project that I was working on encountered an issue because of this. Hopefully your fix will be put in.

**Comment by furzeface** [comment]
Yep as soon as I'm back from a holiday and have a laptop!

**Comment by spywen** [comment]
Np ;) thanks ;) Enjoy the rest of your holiday !!!

**Comment by furzeface** [comment]
:) thanks. And thanks for the contributions everyone, this is making me get
back into this kind of work - I'll have more free time soon so will be able
to maintain projects more. I've been lacking over the last 6 months!!

**Comment by davinkevin** [comment]
Could you confirm #8 fix this issue ?
